# -*- coding: utf-8 -*-
"""Problem_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K6G6eLZWMi-eDrfVuAEdsb5ep8NWxglZ
"""

from scipy.integrate import dblquad
import numpy as np
import math
def integrand(y, x):
    return y*(x**2+y**2)**2*(math.e)**(-x**2-y**2)

ans, err = dblquad(integrand, -math.inf, math.inf,
                   lambda x: -math.inf,
                   lambda x: math.inf)
print(ans)

from sympy import *
#Calculating the expected value of y (similarly the expected value of x is equal to 0)
x, y = symbols("x y")
f = (y*(x ** 2 + y ** 2)**2*(math.e)**(-x**2-y**2))
res = integrate(f, (y,-math.inf,math.inf ), (x, -math.inf,math.inf))
print(res)

#Comparing the two results

x, y = symbols("x y")
f = (y*x*(x ** 2 + y ** 2)**2*(math.e)**(-x**2-y**2))
res1 = integrate(f, (y,-math.inf,math.inf ), (x, -math.inf,math.inf))
print(res1)



x, y = symbols("x y")
f = (y*(x ** 2 + y ** 2)**2*(math.e)**(-x**2-y**2)*x*(x ** 2 + y ** 2)**2*(math.e)**(-x**2-y**2))
res2 = integrate(f, (y,-math.inf,math.inf ), (x, -math.inf,math.inf))
print(res2)